# Generated by Django 5.0.3 on 2024-03-24 14:44

import Account.validators
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=100)),
                ('sms_code', models.CharField(max_length=6)),
                ('authentication_token', models.UUIDField(blank=True, null=True)),
                ('uuid', models.CharField(max_length=36)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('otp_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'اُ-تی-پی',
                'verbose_name_plural': 'اُ-تی-پی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='ضروری', max_length=50, unique=True, verbose_name='نام کاربری')),
                ('mobile_phone', models.CharField(help_text='ضروری', max_length=11, unique=True, verbose_name='شماره تلفن همراه')),
                ('authentication_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد احراز هویت')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, validators=[Account.validators.validate_email], verbose_name='آدرس ایمیل')),
                ('slug', models.SlugField(max_length=100, verbose_name='اسلاگ (متن داخل URL)')),
                ('is_staff', models.BooleanField(default=False, verbose_name='آیا کارمند است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا فعال است؟')),
                ('date_joined', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ پیوستن')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
