# Generated by Django 5.0.3 on 2024-04-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'فالو', 'verbose_name_plural': 'فالوها'},
        ),
        migrations.AlterModelTable(
            name='follow',
            table='account__follow',
        ),
    ]
