# Generated by Django 5.0.3 on 2024-04-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_follow_options_alter_follow_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_at',
            new_name='followed_at',
        ),
    ]
