# Generated by Django 5.0.3 on 2024-04-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_rename_created_at_follow_followed_at'),
        ('Course', '0003_alter_exam_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletusage',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.exam', verbose_name='آزمون'),
            preserve_default=False,
        ),
    ]
