# Generated by Django 5.0.3 on 2024-04-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_walletusage_exam'),
        ('Course', '0003_alter_exam_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletusage',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.exam', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='walletusage',
            name='video_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.videocourse', verbose_name='دوره ویدئویی'),
        ),
    ]
