# Generated by Django 5.0.3 on 2024-04-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_walletusage_exam_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletUsage',
        ),
    ]
