# Generated by Django 5.0.3 on 2024-04-12 09:27

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_delete_walletusage'),
        ('Course', '0003_alter_exam_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اعلانیه', 'verbose_name_plural': 'اعلانات'},
        ),
        migrations.CreateModel(
            name='FavoriteExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.exam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آزمون مورد علاقه',
                'verbose_name_plural': 'آزمون\u200cهای مورد علاقه',
                'db_table': 'account__favorite_exam',
            },
        ),
    ]
