# Generated by Django 5.0.3 on 2024-04-07 16:54

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0003_remove_comment_author_comment_parent_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Weblog.comment', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ'),
        ),
    ]
