# Generated by Django 5.0.3 on 2024-04-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0004_alter_comment_parent_alter_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='weblog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Weblog.weblog', verbose_name='وبلاگ'),
            preserve_default=False,
        ),
    ]
