# Generated by Django 5.0.3 on 2024-04-07 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0005_comment_weblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='Weblog.comment', verbose_name='وبلاگ'),
        ),
    ]
