# Generated by Django 5.0.3 on 2024-04-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0008_alter_commentlike_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت\u200cها'},
        ),
    ]
