# Generated by Django 5.0.3 on 2024-04-12 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0009_alter_comment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
