# Generated by Django 5.0.3 on 2024-04-12 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0010_comment_likes_delete_commentlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
    ]
