# Generated by Django 5.0.3 on 2024-04-12 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0012_alter_comment_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='weblog_comments_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک\u200cها'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='weblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblog_comments', to='Weblog.weblog', verbose_name='وبلاگ'),
        ),
    ]
