# Generated by Django 5.0.3 on 2024-05-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examanswer',
            old_name='choice_1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='examanswer',
            old_name='choice_2',
            new_name='answer_2',
        ),
        migrations.RenameField(
            model_name='examanswer',
            old_name='choice_3',
            new_name='answer_3',
        ),
        migrations.RenameField(
            model_name='examanswer',
            old_name='choice_4',
            new_name='answer_4',
        ),
    ]
