# Generated by Django 5.0.3 on 2024-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('E', 'ساده'), ('N', 'متوسط'), ('H', 'پیچیده')], default='N', max_length=1, verbose_name='میزان سختی'),
        ),
    ]
