# Generated by Django 5.0.3 on 2024-05-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_rename_choice_1_examanswer_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='صورت سوال'),
        ),
    ]
