# Generated by Django 5.0.3 on 2024-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_alter_examanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertempanswer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
