# Generated by Django 5.0.3 on 2024-05-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_alter_usertempanswer_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='answer_1',
            field=models.CharField(default=1, max_length=100, verbose_name='گزینه 1'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='answer_2',
            field=models.CharField(default=2, max_length=100, verbose_name='گزینه 2'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='answer_3',
            field=models.CharField(default=3, max_length=100, verbose_name='گزینه 3'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='answer_4',
            field=models.CharField(default=4, max_length=100, verbose_name='گزینه 4'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='question_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='شماره سوال'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='true_answer',
            field=models.CharField(blank=True, choices=[('1', 'گزینه 1'), ('2', 'گزینه 2'), ('3', 'گزینه 3'), ('4', 'گزینه 4')], max_length=1, null=True, verbose_name='گزینه صحیح'),
        ),
    ]
