# Generated by Django 5.0.3 on 2024-05-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_examanswer_answer_1_alter_examanswer_answer_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='question_file_name',
        ),
    ]
