# Generated by Django 5.0.3 on 2024-03-24 14:44

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ضروری', max_length=75, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='ضروری', upload_to='home/hero-banner/image/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='ضروری', verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='ویرایش شده در تاریخ')),
            ],
            options={
                'verbose_name': 'هیرو بنر',
                'verbose_name_plural': 'هیرو بنر\u200cها',
                'ordering': ('-created_at',),
            },
        ),
    ]
