# Generated by Django 5.0.3 on 2024-05-03 09:03

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='880x330', upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 1',
                'verbose_name_plural': 'بنرهای 1',
                'db_table': 'home__banner_1',
            },
        ),
        migrations.CreateModel(
            name='Banner10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 10',
                'verbose_name_plural': 'بنرهای 10',
                'db_table': 'home__banner_10',
            },
        ),
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='1300x400', upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 2',
                'verbose_name_plural': 'بنرهای 2',
                'db_table': 'home__banner_2',
            },
        ),
        migrations.CreateModel(
            name='Banner3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='880x330', upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 3',
                'verbose_name_plural': 'بنرهای 3',
                'db_table': 'home__banner_3',
            },
        ),
        migrations.CreateModel(
            name='Banner4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='880x330', upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 4',
                'verbose_name_plural': 'بنرهای 4',
                'db_table': 'home__banner_4',
            },
        ),
        migrations.CreateModel(
            name='Banner5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='280x74', upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 5',
                'verbose_name_plural': 'بنرهای 5',
                'db_table': 'home__banner_5',
            },
        ),
        migrations.CreateModel(
            name='Banner6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 6',
                'verbose_name_plural': 'بنرهای 6',
                'db_table': 'home__banner_6',
            },
        ),
        migrations.CreateModel(
            name='Banner7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 7',
                'verbose_name_plural': 'بنرهای 7',
                'db_table': 'home__banner_7',
            },
        ),
        migrations.CreateModel(
            name='Banner8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 8',
                'verbose_name_plural': 'بنرهای 8',
                'db_table': 'home__banner_8',
            },
        ),
        migrations.CreateModel(
            name='Banner9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'بنر 9',
                'verbose_name_plural': 'بنرهای 9',
                'db_table': 'home__banner_9',
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='تیتر')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='1300x400', upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'هیرو بنر',
                'verbose_name_plural': 'هیرو بنرها',
                'db_table': 'home__hero_banner',
            },
        ),
    ]
