# Generated by Django 5.0.3 on 2024-05-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner10',
        ),
        migrations.DeleteModel(
            name='Banner6',
        ),
        migrations.DeleteModel(
            name='Banner7',
        ),
        migrations.DeleteModel(
            name='Banner8',
        ),
        migrations.DeleteModel(
            name='Banner9',
        ),
        migrations.AlterModelOptions(
            name='banner1',
            options={'verbose_name': 'بنر صفحه اصلی - پایین چرا سایت ما (اولین بنر سمت راست و دومین بنر سمت چپ) (2 بنر)', 'verbose_name_plural': 'بنرهای صفحه اصلی - پایین چرا سایت ما (اولین بنر سمت راست و دومین بنر سمت چپ) (2 بنر)'},
        ),
        migrations.AlterModelOptions(
            name='banner2',
            options={'verbose_name': 'بنر پایین درباره اسم وبسایت چی میشنویم (1 بنر)', 'verbose_name_plural': 'بنرهای پایین درباره اسم وبسایت چی میشنویم (1 بنر)'},
        ),
        migrations.AlterModelOptions(
            name='banner3',
            options={'verbose_name': 'بنر صفحه اصلی - پایین آخرین آزمون\u200c\u200cها (اولین بنر سمت راست و دومین بنر سمت چپ) (2 بنر)', 'verbose_name_plural': 'بنرهای صفحه اصلی - پایین آخرین آزمون\u200c\u200cها (اولین بنر سمت راست و دومین بنر سمت چپ) (2 بنر)'},
        ),
        migrations.AlterModelOptions(
            name='banner4',
            options={'verbose_name': 'بنر صفحه آزمون - سمت راست آزمون (3 بنر)', 'verbose_name_plural': 'بنرهای صفحه آزمون - سمت راست آزمون (3 بنر)'},
        ),
        migrations.AlterModelOptions(
            name='banner5',
            options={'verbose_name': 'بنر صفحه آزمون - سمت چپ آزمون (3 بنر)', 'verbose_name_plural': 'بنرهای صفحه آزمون - سمت چپ آزمون (3 بنر)'},
        ),
        migrations.AlterModelOptions(
            name='herobanner',
            options={'verbose_name': 'هیرو بنر (نامحدود)', 'verbose_name_plural': 'هیرو بنرها (نامحدود)'},
        ),
    ]
